-- Create a table for public profiles
create table profiles (
  id uuid references auth.users not null primary key,
  updated_at timestamp with time zone,
  email text unique,
  persona text
);

-- Set up Row Level Security (RLS)
alter table profiles
  enable row level security;

create policy "Public profiles are viewable by everyone." on profiles
  for select using (true);

create policy "Users can insert their own profile." on profiles
  for insert with check (auth.uid() = id);

create policy "Users can update own profile." on profiles
  for update using (auth.uid() = id);

-- Create a table for flashcards
create table flashcards (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  created_at timestamp with time zone default now(),
  scenario text,
  question text not null,
  user_answer text,
  ai_correction text,
  ai_formal_answer text,
  ai_native_answer text,
  status text default 'new',
  next_review_date date
);

-- Set up Row Level Security (RLS) for flashcards
alter table flashcards
  enable row level security;

create policy "Users can view their own flashcards." on flashcards
  for select using (auth.uid() = user_id);

create policy "Users can create flashcards for themselves." on flashcards
  for insert with check (auth.uid() = user_id);

create policy "Users can update their own flashcards." on flashcards
  for update using (auth.uid() = user_id);

-- This trigger automatically creates a profile entry when a new user signs up
create function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, email)
  values (new.id, new.email);
  return new;
end;
$$ language plpgsql security_definer;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
